<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * English strings for the PlayerGroup module.
 *
 * @package    mod_playergroup
 * @copyright  2026 Jean Lúcio
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

// phpcs:disable moodle.Files.LineLength

$string['acceptinvite'] = 'Accept';
$string['activityclosed'] = 'This activity is no longer accepting group formations.';
$string['activityclosedmsg'] = 'This activity has closed. Group formation is no longer allowed.';
$string['activitynotopen'] = 'This activity is not yet open for group formation.';
$string['activityopensfrom'] = 'This activity will open for group formation on {$a}.';
$string['alreadyingroup'] = 'You already belong to a group in this activity.';
$string['availability'] = 'Availability';
$string['canleave'] = 'Allow students to leave their group';
$string['cannotleavegroup'] = 'The teacher has disabled the option to leave a group.';
$string['completionjoingroup'] = 'Student must join or create a group';
$string['completionjoingroup_desc'] = 'Must belong to a group to complete';
$string['completionjoingroupgroup'] = 'Require group affiliation';
$string['creategroup'] = 'Create Group';
$string['currentmembers'] = 'Current members';
$string['defaultgroupingname'] = 'Groups of';
$string['deletegroups'] = 'Delete groups and grouping on activity deletion';
$string['deletegroupswarning'] = 'Warning: if checked, deleting this activity will permanently remove all groups and the grouping created for it. To delete the activity but keep the groups, uncheck this option before deleting.';
$string['description'] = 'Description';
$string['editgroup'] = 'Edit Group';
$string['gamerules'] = 'Game and Team Rules';
$string['grade'] = 'Foundation reward (grade)';
$string['groupbadge'] = 'Badge / Emoji';
$string['groupclosed'] = 'Closed (invite only)';
$string['groupcreated'] = 'Your group was created successfully!';
$string['groupfull'] = 'Full';
$string['groupingdescription'] = 'Automated grouping generated by PlayerGroup for the activity: {$a}';
$string['groupingmode'] = 'Grouping';
$string['groupingmode_existing'] = 'Use an existing grouping';
$string['groupingmode_new'] = 'Create a new grouping';
$string['groupingmode_none'] = 'No grouping';
$string['groupingname'] = 'Grouping name';
$string['groupisfull'] = 'This group is already full.';
$string['groupjoined'] = 'You joined the group successfully!';
$string['groupleft'] = 'You have left the group.';
$string['groupopen'] = 'Open';
$string['grouppassword'] = 'Group password';
$string['groupprotected'] = 'Protected (password)';
$string['groups_title'] = 'Activity Groups';
$string['groupupdated'] = 'Your group was updated successfully!';
$string['invitealreadyhandled'] = 'This invitation has already been responded to.';
$string['invitealreadysent'] = 'A pending invite for this student already exists.';
$string['invitecolleagues'] = 'Invite Colleagues';
$string['invitedby'] = 'From: {$a}';
$string['invitemessage'] = 'You have been invited to join the group \'{$a->group}\' by {$a->sender}.';
$string['invitepending'] = 'Group invitation';
$string['inviterejected'] = 'Invitation declined.';
$string['invitesent'] = 'Invitation sent!';
$string['joingroup'] = 'Join Group';
$string['leader'] = 'Leader';
$string['leadernamed'] = 'Leader: {$a}';
$string['leavegroup'] = 'Leave Group';
$string['leavegroupconfirm'] = 'Are you sure you want to leave this group?';
$string['maxmembers'] = 'Maximum members per group';
$string['messageprovider:invite'] = 'Group invitation';
$string['minmembers'] = 'Minimum members per group';
$string['modulename'] = 'PlayerGroup';
$string['modulename_help'] = 'PlayerGroup allows students to autonomously create groups and invite peers, integrating with gamification ecosystems.';
$string['modulenameplural'] = 'PlayerGroups';
$string['name'] = 'Activity name';
$string['nocolleagueswithoutgroup'] = 'All enrolled students already belong to a group.';
$string['nogroups'] = 'No groups have been created yet. Be the first!';
$string['nogroupyet'] = 'You have not joined a group yet. Create a new group or join an existing one.';
$string['notingroup'] = 'You are not a member of any group in this activity.';
$string['onegrouponly'] = 'You can only belong to one group in this activity.';
$string['passwordkeepblank'] = 'Leave blank to keep the current password';
$string['playergroup:addinstance'] = 'Add a new PlayerGroup activity';
$string['playergroup:creategroup'] = 'Create new groups';
$string['playergroup:manageinvites'] = 'Send and manage group invites';
$string['playergroup:view'] = 'View PlayerGroup content';
$string['pluginadministration'] = 'PlayerGroup administration';
$string['pluginname'] = 'PlayerGroup';
$string['privacy'] = 'Privacy';
$string['receivedinvites'] = 'Pending Invitations';
$string['rejectinvite'] = 'Decline';
$string['sendinvite'] = 'Invite';
$string['showonlyavailable'] = 'Show only available groups';
$string['tab_groups'] = 'Groups';
$string['tab_mygroup'] = 'My Group';
$string['timeclose'] = 'Open until';
$string['timeopen'] = 'Open from';
$string['wrongpassword'] = 'Incorrect password.';
