<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * English strings for the PlayerGroup module.
 *
 * @package    mod_playergroup
 * @copyright  2026 Jean Lúcio
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['alreadyingroup'] = 'You already belong to a group in this activity.';
$string['availability'] = 'Availability';
$string['canleave'] = 'Allow students to leave their group';
$string['completionjoingroup'] = 'Student must join or create a group';
$string['completionjoingroup_desc'] = 'Must belong to a group to complete';
$string['completionjoingroupgroup'] = 'Require group affiliation';
$string['creategroup'] = 'Create Group';
$string['currentmembers'] = 'Current members';
$string['defaultgroupingname'] = 'Groups of';
$string['deletegroups'] = 'Delete groups and grouping on activity deletion';
$string['deletegroupswarning'] = 'Warning: if checked, deleting this activity will permanently remove all groups and the grouping created for it. To delete the activity but keep the groups, uncheck this option before deleting.';
$string['description'] = 'Description';
$string['gamerules'] = 'Game and Team Rules';
$string['grade'] = 'Foundation reward (grade)';
$string['groupbadge'] = 'Badge / Emoji';
$string['groupcreated'] = 'Your group was created successfully!';
$string['groupingdescription'] = 'Automated grouping generated by PlayerGroup for the activity: {$a}';
$string['groups_title'] = 'Activity Groups';
$string['joingroup'] = 'Join Group';
$string['maxmembers'] = 'Maximum members per group';
$string['messageprovider:invite'] = 'Group invitation';
$string['minmembers'] = 'Minimum members per group';
$string['modulename'] = 'PlayerGroup';
$string['modulename_help'] = 'PlayerGroup allows students to autonomously create groups and invite peers, integrating with gamification ecosystems.';
$string['modulenameplural'] = 'PlayerGroups';
$string['name'] = 'Activity name';
$string['nogroups'] = 'No groups have been created yet. Be the first!';
$string['playergroup:addinstance'] = 'Add a new PlayerGroup activity';
$string['playergroup:creategroup'] = 'Create new groups';
$string['playergroup:manageinvites'] = 'Send and manage group invites';
$string['playergroup:view'] = 'View PlayerGroup content';
$string['pluginadministration'] = 'PlayerGroup administration';
$string['pluginname'] = 'PlayerGroup';
$string['timeclose'] = 'Open until';
$string['timeopen'] = 'Open from';
