<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * English strings for the PlayerGroup module.
 *
 * @package    mod_playergroup
 * @copyright  2026 Jean Lúcio
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

// phpcs:disable moodle.Files.LineLength

$string['acceptinvite'] = 'Accept';
$string['activityclosed'] = 'This activity is no longer accepting group formations.';
$string['activityclosedmsg'] = 'This activity has closed. Group formation is no longer allowed.';
$string['activitylog'] = 'Activity Log';
$string['activitylog_empty'] = 'No activity recorded yet.';
$string['activitynotopen'] = 'This activity is not yet open for group formation.';
$string['activityopensfrom'] = 'This activity will open for group formation on {$a}.';
$string['alreadyingroup'] = 'You already belong to a group in this activity.';
$string['availability'] = 'Availability';
$string['back'] = 'Back';
$string['canleave'] = 'Allow students to leave their group';
$string['cannotleavegroup'] = 'The teacher has disabled the option to leave a group.';
$string['completionjoingroup'] = 'Student must join or create a group';
$string['completionjoingroup_desc'] = 'Must belong to a group to complete';
$string['completionjoingroupgroup'] = 'Require group affiliation';
$string['creategroup'] = 'Create Group';
$string['defaultgroupingname'] = 'Groups of';
$string['deleteemptygroups'] = 'Automatically delete empty groups';
$string['deleteemptygroups_help'] = 'When enabled, a group will be deleted automatically when its last member leaves. All pending invitations to that group will also be cancelled. This setting only takes effect when students are allowed to leave groups.';
$string['deletegroups'] = 'Delete groups and grouping on activity deletion';
$string['deletegroupswarning'] = 'Warning: if checked, deleting this activity will permanently remove all groups and the grouping created for it. To delete the activity but keep the groups, uncheck this option before deleting.';
$string['description'] = 'Description';
$string['editgroup'] = 'Edit Group';
$string['editgroup_named'] = 'Edit group {$a}';
$string['event_group_created'] = 'Group created';
$string['event_group_deleted'] = 'Group automatically deleted';
$string['event_invite_accepted'] = 'Invitation accepted';
$string['event_member_joined'] = 'Member joined group';
$string['event_member_left'] = 'Member left group';
$string['export_csv'] = 'Export to CSV';
$string['export_excel'] = 'Export to Excel';
$string['gamerules'] = 'Game and Team Rules';
$string['grade'] = 'Foundation reward (grade)';
$string['gradeautonotice'] = 'Grading is automatic: the student receives the configured points as soon as they join or create a group. The grade is permanent — it is not removed if the student leaves the group later.';
$string['groupbadge'] = 'Badge / Emoji';
$string['groupclosed'] = 'Closed (invite only)';
$string['groupcreated'] = 'Your group was created successfully!';
$string['groupfull'] = 'Full';
$string['groupingdescription'] = 'Automated grouping generated by PlayerGroup for the activity: {$a}';
$string['groupingmode'] = 'Grouping';
$string['groupingmode_existing'] = 'Use an existing grouping';
$string['groupingmode_new'] = 'Create a new grouping';
$string['groupingmode_none'] = 'No grouping';
$string['groupingname'] = 'Grouping name';
$string['groupisfull'] = 'This group is already full.';
$string['groupjoined'] = 'You joined the group successfully!';
$string['groupleft'] = 'You have left the group.';
$string['grouplockbusy'] = 'Another request for this group is already being processed. Please try again in a moment.';
$string['groupmembers_named'] = 'Members of {$a}';
$string['groupname'] = 'Group name';
$string['groupopen'] = 'Open';
$string['grouppassword'] = 'Group password';
$string['groupprotected'] = 'Protected (password)';
$string['groups_title'] = 'Activity Groups';
$string['groupsreport'] = 'Groups and Members';
$string['groupsreport_empty'] = 'No groups have been created in this activity yet.';
$string['groupupdated'] = 'Your group was updated successfully!';
$string['invitealreadyhandled'] = 'This invitation has already been responded to.';
$string['invitealreadysent'] = 'A pending invite for this student already exists.';
$string['invitecolleagues'] = 'Invite Colleagues';
$string['invitedby'] = 'From: {$a}';
$string['invitemessage'] = 'You have been invited to join the group \'{$a->group}\' by {$a->sender}.';
$string['invitepending'] = 'Group invitation';
$string['inviterejected'] = 'Invitation declined.';
$string['invitesent'] = 'Invitation sent!';
$string['joinfailed'] = 'Could not join the group. You may not be enrolled in this course.';
$string['joingroup'] = 'Join Group';
$string['joingroup_named'] = 'Join group {$a}';
$string['leader'] = 'Leader';
$string['leadernamed'] = 'Leader: {$a}';
$string['leavegroup'] = 'Leave Group';
$string['leavegroup_named'] = 'Leave group {$a}';
$string['leavegroupconfirm'] = 'Are you sure you want to leave this group?';
$string['maxmembers'] = 'Maximum members per group';
$string['member'] = 'Member';
$string['messageprovider:invite'] = 'Group invitation';
$string['minmembers'] = 'Minimum members per group';
$string['mobile_back'] = 'Back';
$string['mobile_cancel'] = 'Cancel';
$string['mobile_creategroup'] = 'Create group';
$string['mobile_decline'] = 'Decline';
$string['mobile_editgroup'] = 'Edit group';
$string['mobile_enterpassword'] = 'Enter group password';
$string['mobile_error'] = 'An error occurred. Please try again.';
$string['mobile_groupname_required'] = 'Group name is required.';
$string['mobile_inviteaccept'] = 'Accept';
$string['mobile_invitedecline'] = 'Decline';
$string['mobile_inviteusers'] = 'Invite members';
$string['mobile_joinopen'] = 'Join';
$string['mobile_joinprotected'] = 'Join (password required)';
$string['mobile_leaveconfirm'] = 'Are you sure you want to leave this group?';
$string['mobile_nogroups'] = 'No groups yet. Be the first to create one!';
$string['mobile_noinvites'] = 'No pending invitations.';
$string['mobile_passwordkeep'] = 'Leave blank to keep the current password';
$string['mobile_privacyclosed'] = 'Closed (invitation only)';
$string['mobile_privacyopen'] = 'Open';
$string['mobile_privacyprotected'] = 'Protected (password)';
$string['mobile_save'] = 'Save';
$string['modulename'] = 'PlayerGroup';
$string['modulename_help'] = 'PlayerGroup allows students to autonomously create groups and invite peers, integrating with gamification ecosystems.';
$string['modulenameplural'] = 'PlayerGroups';
$string['name'] = 'Activity name';
$string['nocolleagueswithoutgroup'] = 'All enrolled students already belong to a group.';
$string['nogroups'] = 'No groups have been created yet. Be the first!';
$string['nogroupyet'] = 'You have not joined a group yet. Create a new group or join an existing one.';
$string['notingroup'] = 'You are not a member of any group in this activity.';
$string['onegrouponly'] = 'You can only belong to one group in this activity.';
$string['passwordkeepblank'] = 'Leave blank to keep the current password';
$string['playergroup:addinstance'] = 'Add a new PlayerGroup activity';
$string['playergroup:creategroup'] = 'Create new groups';
$string['playergroup:manage'] = 'Manage PlayerGroup activity';
$string['playergroup:manageinvites'] = 'Send and manage group invites';
$string['playergroup:view'] = 'View PlayerGroup content';
$string['pluginadministration'] = 'PlayerGroup administration';
$string['pluginname'] = 'PlayerGroup';
$string['privacy'] = 'Privacy';
$string['privacy:metadata:creatorid'] = 'The ID of the user who created the group.';
$string['privacy:metadata:playergroup_invites'] = 'Stores group invitations sent and received by students.';
$string['privacy:metadata:playergroup_meta'] = 'Stores metadata for groups created by students in this activity.';
$string['privacy:metadata:receiverid'] = 'The ID of the user who received the group invitation.';
$string['privacy:metadata:senderid'] = 'The ID of the user who sent the group invitation.';
$string['privacy:metadata:timecreated'] = 'The time at which this record was created.';
$string['receivedinvites'] = 'Pending Invitations';
$string['rejectinvite'] = 'Decline';
$string['report_action'] = 'Action';
$string['report_date'] = 'Date';
$string['report_group'] = 'Group';
$string['report_name'] = 'Name';
$string['report_role'] = 'Role';
$string['report_user'] = 'User';
$string['sendinvite'] = 'Invite';
$string['showonlyavailable'] = 'Show only available groups';
$string['tab_groups'] = 'Groups';
$string['tab_mygroup'] = 'My Group';
$string['timeclose'] = 'Open until';
$string['timeopen'] = 'Open from';
$string['usernotenrolled'] = 'That user is not enrolled in this course.';
$string['viewmembers_named'] = 'View members of {$a}';
$string['viewreport'] = 'View Report';
$string['wrongpassword'] = 'Incorrect password.';
